"""add user_role enum and drop is_superuser

Revision ID: 27ca66ab8658
Revises: e545e5042741
Create Date: 2026-08-21 02:03:08.600225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '27ca66ab8658'
down_revision: Union[str, Sequence[str], None] = 'e545e5042741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role_enum = postgresql.ENUM(
    "guest", "user", "trusted", "moderator", "admin", name="user_role"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users",
        sa.Column(
            "role",
            user_role_enum,
            server_default="user",
            nullable=False,
        ),
    )
    op.execute("UPDATE users SET role = 'admin' WHERE is_superuser = true")
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.execute("UPDATE users SET is_superuser = true WHERE role = 'admin'")
    op.drop_column("users", "role")
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
