"""add thumbhash

Revision ID: 2f68588fcc4a
Revises: a9db84802c03
Create Date: 2026-07-22 14:24:13.417453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f68588fcc4a'
down_revision: Union[str, Sequence[str], None] = 'a9db84802c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.add_column('album_covers', sa.Column('thumbhash', sa.String(length=128), nullable=True))
    op.drop_index(op.f('idx_albums_folder_name'), table_name='albums')
    op.create_index('idx_albums_folder_name_trgm', 'albums', ['original_folder_name'], unique=False, postgresql_using='gin', postgresql_ops={'original_folder_name': 'gin_trgm_ops'})
    op.create_index('idx_albums_title_orig_trgm', 'albums', ['title_original'], unique=False, postgresql_using='gin', postgresql_ops={'title_original': 'gin_trgm_ops'})
    op.create_index('idx_artists_name_orig_trgm', 'artists', ['name_original'], unique=False, postgresql_using='gin', postgresql_ops={'name_original': 'gin_trgm_ops'})
    op.drop_index(op.f('idx_discs_catalog_number'), table_name='discs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_discs_catalog_number'), 'discs', ['catalog_number'], unique=False)
    op.drop_index('idx_artists_name_orig_trgm', table_name='artists', postgresql_using='gin', postgresql_ops={'name_original': 'gin_trgm_ops'})
    op.drop_index('idx_albums_title_orig_trgm', table_name='albums', postgresql_using='gin', postgresql_ops={'title_original': 'gin_trgm_ops'})
    op.drop_index('idx_albums_folder_name_trgm', table_name='albums', postgresql_using='gin', postgresql_ops={'original_folder_name': 'gin_trgm_ops'})
    op.create_index(op.f('idx_albums_folder_name'), 'albums', ['original_folder_name'], unique=False)
    op.drop_column('album_covers', 'thumbhash')
    # ### end Alembic commands ###
