"""add artists

Revision ID: 43be3c552d81
Revises: 93e065b0fcb4
Create Date: 2026-07-22 12:07:48.383469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43be3c552d81'
down_revision: Union[str, Sequence[str], None] = '93e065b0fcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('album_categories', 'category',
               existing_type=postgresql.ENUM('ROCK', 'POP', 'ELECTRONIC', 'CLASSICAL', 'SOUNDTRACK', 'GAME_OST', 'DOUJIN', 'VOCALOID', 'ANIME', 'JPOP', 'VNS', name='librarycategory'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('discs', 'media_type',
               existing_type=postgresql.ENUM('CD', 'DVD', 'BD', 'CASSETTE', 'VINYL', 'WEB', name='mediatype'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('discs', 'container_format',
               existing_type=postgresql.ENUM('TRACKS', 'ISO', 'MDF', 'BIN_CUE', 'CDI', 'IMG', 'VOB', name='containerformat'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('discs', 'log_type',
               existing_type=postgresql.ENUM('EAC', 'XLD', 'EZCD', 'CUERIPPER', 'CYANRIP', 'WHIPPER', name='logtype'),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('tracks', 'audio_codec',
               existing_type=postgresql.ENUM('FLAC', 'MP3', 'ALAC', 'AAC', 'PCM', 'AC3', 'DTS', 'WMA', 'WAVPACK', name='audiocodec'),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('tracks', 'video_codec',
               existing_type=postgresql.ENUM('MPEG2', 'H264', 'HEVC', 'VC1', name='videocodec'),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('tracks', 'bitrate_mode',
               existing_type=postgresql.ENUM('CBR', 'VBR', 'ABR', name='bitratemode'),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'bitrate_mode',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('CBR', 'VBR', 'ABR', name='bitratemode'),
               existing_nullable=True)
    op.alter_column('tracks', 'video_codec',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('MPEG2', 'H264', 'HEVC', 'VC1', name='videocodec'),
               existing_nullable=True)
    op.alter_column('tracks', 'audio_codec',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('FLAC', 'MP3', 'ALAC', 'AAC', 'PCM', 'AC3', 'DTS', 'WMA', 'WAVPACK', name='audiocodec'),
               existing_nullable=True)
    op.alter_column('discs', 'log_type',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('EAC', 'XLD', 'EZCD', 'CUERIPPER', 'CYANRIP', 'WHIPPER', name='logtype'),
               existing_nullable=True)
    op.alter_column('discs', 'container_format',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('TRACKS', 'ISO', 'MDF', 'BIN_CUE', 'CDI', 'IMG', 'VOB', name='containerformat'),
               existing_nullable=False)
    op.alter_column('discs', 'media_type',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('CD', 'DVD', 'BD', 'CASSETTE', 'VINYL', 'WEB', name='mediatype'),
               existing_nullable=False)
    op.alter_column('album_categories', 'category',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('ROCK', 'POP', 'ELECTRONIC', 'CLASSICAL', 'SOUNDTRACK', 'GAME_OST', 'DOUJIN', 'VOCALOID', 'ANIME', 'JPOP', 'VNS', name='librarycategory'),
               existing_nullable=False)
    # ### end Alembic commands ###
