"""create_music_archival_schema

Revision ID: 4b6a0d51cd15
Revises: 07c16344a1c1
Create Date: 2026-07-18 10:50:10.346297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6a0d51cd15'
down_revision: Union[str, Sequence[str], None] = '07c16344a1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_original', sa.String(length=512), nullable=False),
    sa.Column('name_translated', sa.String(length=512), nullable=True),
    sa.Column('is_circle', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artists'))
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('short_name', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('short_name', name=op.f('uq_events_short_name'))
    )
    op.create_table('franchises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_original', sa.String(length=512), nullable=False),
    sa.Column('name_translated', sa.String(length=512), nullable=True),
    sa.Column('franchise_type', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_franchises'))
    )
    op.create_table('albums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title_original', sa.String(length=512), nullable=False),
    sa.Column('title_translated', sa.String(length=512), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('franchise_id', sa.UUID(), nullable=True),
    sa.Column('library_category', sa.Enum('ROCK', 'POP', 'ELECTRONIC', 'CLASSICAL', 'SOUNDTRACK', 'GAME_OST', 'DOUJIN', 'VOCALOID', 'ANIME', 'JPOP', 'VNS', name='librarycategory'), nullable=False),
    sa.Column('original_folder_name', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_albums_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], name=op.f('fk_albums_franchise_id_franchises'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_albums'))
    )
    op.create_index('idx_albums_folder_name', 'albums', ['original_folder_name'], unique=False)
    op.create_index('idx_albums_library_category', 'albums', ['library_category'], unique=False)
    op.create_index('idx_albums_release_date_desc', 'albums', [sa.literal_column('release_date DESC')], unique=False)
    op.create_table('album_archives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('archive_name', sa.String(length=512), nullable=False),
    sa.Column('encryption_password', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_album_archives_album_id_albums'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_album_archives'))
    )
    op.create_table('album_artists',
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_album_artists_album_id_albums'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_album_artists_artist_id_artists'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('album_id', 'artist_id', 'role', name=op.f('pk_album_artists'))
    )
    op.create_table('album_covers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_album_covers_album_id_albums'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_album_covers')),
    sa.UniqueConstraint('album_id', name=op.f('uq_album_covers_album_id'))
    )
    op.create_table('discs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('disc_number', sa.Integer(), nullable=False),
    sa.Column('catalog_number', sa.String(length=64), nullable=True),
    sa.Column('media_type', sa.Enum('CD', 'DVD', 'BD', 'CASSETTE', 'VINYL', 'WEB', name='mediatype'), nullable=False),
    sa.Column('container_format', sa.Enum('TRACKS', 'ISO', 'MDF', 'BIN_CUE', 'CDI', 'IMG', 'VOB', name='containerformat'), nullable=False),
    sa.Column('log_type', sa.Enum('EAC', 'XLD', 'EZCD', 'CUERIPPER', 'CYANRIP', 'WHIPPER', name='logtype'), nullable=True),
    sa.Column('log_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('log_score <= 100', name=op.f('ck_discs_chk_valid_log_score')),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_discs_album_id_albums'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discs'))
    )
    op.create_index('idx_discs_catalog_number', 'discs', ['catalog_number'], unique=False)
    op.create_index('ux_discs_album_number', 'discs', ['album_id', 'disc_number'], unique=True)
    op.create_table('external_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('site_name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('remote_item_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_external_links_album_id_albums'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_links'))
    )
    op.create_table('archive_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archive_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=128), nullable=False),
    sa.Column('download_url', sa.String(length=2048), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['album_archives.id'], name=op.f('fk_archive_links_archive_id_album_archives'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archive_links'))
    )
    op.create_table('tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disc_id', sa.UUID(), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('title_original', sa.String(length=512), nullable=False),
    sa.Column('title_translated', sa.String(length=512), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('audio_codec', sa.Enum('FLAC', 'MP3', 'ALAC', 'AAC', 'PCM', 'AC3', 'DTS', 'WMA', 'WAVPACK', name='audiocodec'), nullable=True),
    sa.Column('video_codec', sa.Enum('MPEG2', 'H264', 'HEVC', 'VC1', name='videocodec'), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('bitrate_mode', sa.Enum('CBR', 'VBR', 'ABR', name='bitratemode'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('track_number > 0', name=op.f('ck_tracks_chk_track_number_positive')),
    sa.ForeignKeyConstraint(['disc_id'], ['discs.id'], name=op.f('fk_tracks_disc_id_discs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks'))
    )
    op.create_index('ux_tracks_disc_number', 'tracks', ['disc_id', 'track_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_tracks_disc_number', table_name='tracks')
    op.drop_table('tracks')
    op.drop_table('archive_links')
    op.drop_table('external_links')
    op.drop_index('ux_discs_album_number', table_name='discs')
    op.drop_index('idx_discs_catalog_number', table_name='discs')
    op.drop_table('discs')
    op.drop_table('album_covers')
    op.drop_table('album_artists')
    op.drop_table('album_archives')
    op.drop_index('idx_albums_release_date_desc', table_name='albums')
    op.drop_index('idx_albums_library_category', table_name='albums')
    op.drop_index('idx_albums_folder_name', table_name='albums')
    op.drop_table('albums')
    op.drop_table('franchises')
    op.drop_table('events')
    op.drop_table('artists')
    # ### end Alembic commands ###
