"""add event original dates

Revision ID: 78707e7fab10
Revises: 7de699eecdf0
Create Date: 2026-08-10 07:48:36.680425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78707e7fab10'
down_revision: Union[str, Sequence[str], None] = '7de699eecdf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_albums_aliases_trgm'), table_name='albums', postgresql_ops={'(aliases::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_artists_aliases_trgm'), table_name='artists', postgresql_ops={'(aliases::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.add_column('events', sa.Column('original_start_date', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('original_end_date', sa.Date(), nullable=True))
    op.drop_index(op.f('idx_franchises_aliases_trgm'), table_name='franchises', postgresql_ops={'(aliases::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_franchises_aliases_trgm'), 'franchises', [sa.literal_column('(aliases::text)')], unique=False, postgresql_ops={'(aliases::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_column('events', 'original_end_date')
    op.drop_column('events', 'original_start_date')
    op.create_index(op.f('idx_artists_aliases_trgm'), 'artists', [sa.literal_column('(aliases::text)')], unique=False, postgresql_ops={'(aliases::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_albums_aliases_trgm'), 'albums', [sa.literal_column('(aliases::text)')], unique=False, postgresql_ops={'(aliases::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
