"""add track artists, publisher, labels, categories

Revision ID: 93e065b0fcb4
Revises: 4b6a0d51cd15
Create Date: 2026-07-20 11:31:02.954488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93e065b0fcb4'
down_revision: Union[str, Sequence[str], None] = '4b6a0d51cd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_categories',
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ROCK', 'POP', 'ELECTRONIC', 'CLASSICAL', 'SOUNDTRACK', 'GAME_OST', 'DOUJIN', 'VOCALOID', 'ANIME', 'JPOP', 'VNS', name='librarycategory'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_album_categories_album_id_albums'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'category', name=op.f('pk_album_categories'))
    )
    op.create_table('track_artists',
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_track_artists_artist_id_artists'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_track_artists_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'artist_id', 'role', name=op.f('pk_track_artists'))
    )
    op.add_column('album_archives', sa.Column('hash_sha256', sa.String(length=64), nullable=True))
    op.add_column('album_covers', sa.Column('storage_path', sa.String(length=1024), nullable=False))
    op.drop_column('album_covers', 'image_data')
    op.add_column('albums', sa.Column('label', sa.String(length=255), nullable=True))
    op.add_column('albums', sa.Column('publisher', sa.String(length=255), nullable=True))
    op.add_column('albums', sa.Column('storage_drive', sa.String(length=64), nullable=True))
    op.add_column('albums', sa.Column('relative_path', sa.String(length=1024), nullable=True))
    op.drop_index(op.f('idx_albums_library_category'), table_name='albums')
    op.drop_column('albums', 'library_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('library_category', postgresql.ENUM('ROCK', 'POP', 'ELECTRONIC', 'CLASSICAL', 'SOUNDTRACK', 'GAME_OST', 'DOUJIN', 'VOCALOID', 'ANIME', 'JPOP', 'VNS', name='librarycategory'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_albums_library_category'), 'albums', ['library_category'], unique=False)
    op.drop_column('albums', 'relative_path')
    op.drop_column('albums', 'storage_drive')
    op.drop_column('albums', 'publisher')
    op.drop_column('albums', 'label')
    op.add_column('album_covers', sa.Column('image_data', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('album_covers', 'storage_path')
    op.drop_column('album_archives', 'hash_sha256')
    op.drop_table('track_artists')
    op.drop_table('album_categories')
    # ### end Alembic commands ###
