"""refactor db, add changelog

Revision ID: a9db84802c03
Revises: 43be3c552d81
Create Date: 2026-07-22 13:28:34.845237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9db84802c03'
down_revision: Union[str, Sequence[str], None] = '43be3c552d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_changelogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_album_changelogs_album_id_albums'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_album_changelogs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_album_changelogs'))
    )
    op.create_index('idx_album_changelogs_album_id', 'album_changelogs', ['album_id'], unique=False)
    op.create_index('idx_album_changelogs_user_id', 'album_changelogs', ['user_id'], unique=False)
    op.add_column('album_covers', sa.Column('cover_type', sa.String(length=64), nullable=False))
    op.drop_constraint(op.f('uq_album_covers_album_id'), 'album_covers', type_='unique')
    op.drop_column('album_covers', 'width')
    op.drop_column('album_covers', 'height')
    op.drop_column('album_covers', 'mime_type')
    op.add_column('albums', sa.Column('release_year', sa.SmallInteger(), nullable=True))
    op.add_column('albums', sa.Column('release_month', sa.SmallInteger(), nullable=True))
    op.add_column('albums', sa.Column('release_day', sa.SmallInteger(), nullable=True))
    op.add_column('albums', sa.Column('release_date_sort', sa.Date(), nullable=True))
    op.drop_index(op.f('idx_albums_release_date_desc'), table_name='albums')
    op.create_index('idx_albums_release_date_sort_desc', 'albums', [sa.literal_column('release_date_sort DESC')], unique=False)
    op.drop_column('albums', 'release_date')
    op.add_column('discs', sa.Column('raw_log_text', sa.Text(), nullable=True))
    op.add_column('discs', sa.Column('raw_cue_text', sa.Text(), nullable=True))
    op.add_column('discs', sa.Column('accuraterip_summary', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('event_date', sa.Date(), nullable=True))
    op.drop_column('events', 'event_type')
    op.drop_column('external_links', 'remote_item_id')
    op.add_column('tracks', sa.Column('is_instrumental', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=128), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('tracks', 'is_instrumental')
    op.add_column('external_links', sa.Column('remote_item_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('events', 'event_date')
    op.drop_column('discs', 'accuraterip_summary')
    op.drop_column('discs', 'raw_cue_text')
    op.drop_column('discs', 'raw_log_text')
    op.add_column('albums', sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index('idx_albums_release_date_sort_desc', table_name='albums')
    op.create_index(op.f('idx_albums_release_date_desc'), 'albums', [sa.literal_column('release_date DESC')], unique=False)
    op.drop_column('albums', 'release_date_sort')
    op.drop_column('albums', 'release_day')
    op.drop_column('albums', 'release_month')
    op.drop_column('albums', 'release_year')
    op.add_column('album_covers', sa.Column('mime_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('album_covers', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('album_covers', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_album_covers_album_id'), 'album_covers', ['album_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('album_covers', 'cover_type')
    op.drop_index('idx_album_changelogs_user_id', table_name='album_changelogs')
    op.drop_index('idx_album_changelogs_album_id', table_name='album_changelogs')
    op.drop_table('album_changelogs')
    # ### end Alembic commands ###
