"""refactor events table, remove album categories

Revision ID: b7bac9e63bee
Revises: 2f68588fcc4a
Create Date: 2026-07-24 13:50:12.054198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7bac9e63bee'
down_revision: Union[str, Sequence[str], None] = '2f68588fcc4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album_artists')
    op.drop_table('album_categories')
    op.add_column('albums', sa.Column('album_artist_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_albums_album_artist_id_artists'), 'albums', 'artists', ['album_artist_id'], ['id'], ondelete='SET NULL')
    op.drop_column('artists', 'is_circle')
    op.add_column('events', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('status', sa.String(length=32), server_default='HELD', nullable=False))
    op.drop_column('events', 'event_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('events', 'status')
    op.drop_column('events', 'end_date')
    op.drop_column('events', 'start_date')
    op.add_column('artists', sa.Column('is_circle', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_albums_album_artist_id_artists'), 'albums', type_='foreignkey')
    op.drop_column('albums', 'album_artist_id')
    op.create_table('album_categories',
    sa.Column('album_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_album_categories_album_id_albums'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'category', name=op.f('pk_album_categories'))
    )
    op.create_table('album_artists',
    sa.Column('album_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_album_artists_album_id_albums'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_album_artists_artist_id_artists'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('album_id', 'artist_id', 'role', name=op.f('pk_album_artists'))
    )
    # ### end Alembic commands ###
