"""add labels, publishers and entity metadata

Revision ID: e545e5042741
Revises: fa44c3e955b9
Create Date: 2026-08-12 13:48:12.763400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e545e5042741'
down_revision: Union[str, Sequence[str], None] = 'fa44c3e955b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'labels',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name_original', sa.String(length=512), nullable=False),
        sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
        sa.Column('image_path', sa.String(length=1024), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_labels'))
    )
    op.create_table(
        'publishers',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name_original', sa.String(length=512), nullable=False),
        sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
        sa.Column('image_path', sa.String(length=1024), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_publishers'))
    )
    op.add_column('artists', sa.Column('image_path', sa.String(length=1024), nullable=True))
    op.add_column('artists', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('franchises', sa.Column('image_path', sa.String(length=1024), nullable=True))
    op.add_column('franchises', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('albums', sa.Column('label_id', sa.UUID(), nullable=True))
    op.add_column('albums', sa.Column('publisher_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_albums_label_id_labels'), 'albums', 'labels', ['label_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_albums_publisher_id_publishers'), 'albums', 'publishers', ['publisher_id'], ['id'], ondelete='SET NULL')
    op.drop_column('albums', 'label')
    op.drop_column('albums', 'publisher')
    op.execute("CREATE INDEX IF NOT EXISTS idx_labels_aliases_trgm ON labels USING gin ((aliases::text) gin_trgm_ops)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_publishers_aliases_trgm ON publishers USING gin ((aliases::text) gin_trgm_ops)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_publishers_aliases_trgm")
    op.execute("DROP INDEX IF EXISTS idx_labels_aliases_trgm")
    op.add_column('albums', sa.Column('publisher', sa.String(length=255), nullable=True))
    op.add_column('albums', sa.Column('label', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('fk_albums_publisher_id_publishers'), 'albums', type_='foreignkey')
    op.drop_constraint(op.f('fk_albums_label_id_labels'), 'albums', type_='foreignkey')
    op.drop_column('albums', 'publisher_id')
    op.drop_column('albums', 'label_id')
    op.drop_column('franchises', 'description')
    op.drop_column('franchises', 'image_path')
    op.drop_column('artists', 'description')
    op.drop_column('artists', 'image_path')
    op.drop_table('publishers')
    op.drop_table('labels')
    # ### end Alembic commands ###
