"""add partial dates

Revision ID: fa44c3e955b9
Revises: 6047c72285c2
Create Date: 2026-08-11 04:38:20.615479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa44c3e955b9'
down_revision: Union[str, Sequence[str], None] = '6047c72285c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'events',
        'start_date',
        existing_type=sa.Date(),
        type_=sa.String(length=64),
        postgresql_using='start_date::text'
    )
    op.alter_column(
        'events',
        'end_date',
        existing_type=sa.Date(),
        type_=sa.String(length=64),
        postgresql_using='end_date::text'
    )
    op.alter_column(
        'events',
        'original_start_date',
        existing_type=sa.Date(),
        type_=sa.String(length=64),
        postgresql_using='original_start_date::text'
    )
    op.alter_column(
        'events',
        'original_end_date',
        existing_type=sa.Date(),
        type_=sa.String(length=64),
        postgresql_using='original_end_date::text'
    )
    op.add_column(
        'events',
        sa.Column(
            'start_date_sort',
            sa.Date(),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'start_date_sort')
    op.alter_column(
        'events',
        'original_end_date',
        existing_type=sa.String(length=64),
        type_=sa.Date(),
        postgresql_using='original_end_date::date'
    )
    op.alter_column(
        'events',
        'original_start_date',
        existing_type=sa.String(length=64),
        type_=sa.Date(),
        postgresql_using='original_start_date::date'
    )
    op.alter_column(
        'events',
        'end_date',
        existing_type=sa.String(length=64),
        type_=sa.Date(),
        postgresql_using='end_date::date'
    )
    op.alter_column(
        'events',
        'start_date',
        existing_type=sa.String(length=64),
        type_=sa.Date(),
        postgresql_using='start_date::date'
    )
    # ### end Alembic commands ###
