from src.presentation.schemas.auth import TokenResponseSchema, UserLoginRequestSchema
from src.presentation.schemas.entities import (
    ArtistCreateSchema,
    ArtistResponseSchema,
    EventCreateSchema,
    EventResponseSchema,
    EventUpdateSchema,
    FranchiseCreateSchema,
    FranchiseResponseSchema,
    PaginatedEventsResponseSchema,
)
from src.presentation.schemas.music import (
    AlbumChangelogResponseSchema,
    AlbumDetailResponseSchema,
    AlbumIngestRequestSchema,
    AlbumIngestResponseSchema,
    AlbumSummaryResponseSchema,
    ArchiveIngestSchema,
    ArchiveLinkIngestSchema,
    CoverIngestSchema,
    CoverResponseSchema,
    DiscIngestSchema,
    ExternalLinkIngestSchema,
    PaginatedAlbumsResponseSchema,
    TrackIngestSchema,
)
from src.presentation.schemas.user import UserRegisterRequestSchema, UserResponseSchema


__all__ = [
    "UserRegisterRequestSchema",
    "UserResponseSchema",
    "UserLoginRequestSchema",
    "TokenResponseSchema",
    "TrackIngestSchema",
    "DiscIngestSchema",
    "ArchiveLinkIngestSchema",
    "ArchiveIngestSchema",
    "ExternalLinkIngestSchema",
    "CoverIngestSchema",
    "CoverResponseSchema",
    "AlbumIngestRequestSchema",
    "AlbumIngestResponseSchema",
    "AlbumSummaryResponseSchema",
    "AlbumDetailResponseSchema",
    "AlbumChangelogResponseSchema",
    "PaginatedAlbumsResponseSchema",
    "ArtistCreateSchema",
    "ArtistResponseSchema",
    "EventCreateSchema",
    "EventResponseSchema",
    "EventUpdateSchema",
    "PaginatedEventsResponseSchema",
    "FranchiseCreateSchema",
    "FranchiseResponseSchema",
]
